export const faculty = [
    ['Ms. Archana Kaushik', 'Principal', '../images/principal.png'],
    ['Dr. Madhu Juneja', 'Director Academics', '../images/director.jpeg'],
    ['Ms. Charu', 'Economics', '../images/'],
    ['Ms. Jyoti Chauhan', 'Commerce', '../images/'],
    ['Ms. Pooja Yadav', 'Chemistry', '../images/'],
    ['Mr. Prem Kumar Jha', 'History', '../images/'],
    ['Ms. Madhvi Goyal', 'Biology', '../images/'],
    ['Ms. Kanchan Rani', 'Physics', '../images/'],
    ['Mr. Atul Kumar Gupta', 'Physical Education', '../images/'],
    ['Ms. Shweta Jain', 'Mathematics', '../images/'],
    ['Mr. Prashant Kumar Choudhary', 'English', '../images/'],
    ['Ms. Monika Yadav', 'English', '../images/'],
    ['Ms. Divya Sethi', 'Psychology', '..images/'],
    ['Ms. Sushma Sharma', 'Computer Science', '../images/'],
    ['Ms. Sonali', 'Consellor', '../images/'],
    ['Ms. Arushi', 'Special Educator', '../images/'],
    ['Ms. Monika Popli', 'Incharge Primary Wing', '../images/'],
    ['Ms. Taruna Rani', 'Social Science', '../images/'],
    ['Mr. Karamveer Kataria', 'Mathematics', '../images/'],
    ['Ms. Savera Gupta', 'Science', '../images/'],
    ['Mr. Devender Singh Aswal', 'Science', '../images/'],
    ['Mr. Rizwan Salmani', 'English', '../images/'],
    ['Ms. Geeta Sangwan', 'English', '../images/'],
    ['Ms. Veena Kumari', 'Hindi', '../images/'],
    ['Ms. Poonam Rani', 'Social Science', '../images/'],
    ['Ms. Geeta Sharma', 'Hindi / Sanskrit', '../images/'],
    ['Ms. Rajni Pal', 'Hindi / Sanskrit', '../images/'],
    ['Ms. Indu Bala Sachdeva', 'Mathematics', '../images/'],
    ['Ms. Kiran Bala', 'Hindi / Sanskrit', '../images/'],
    ['Ms. Ashima Sharma', 'All Subjects', '../images/'],
    ['Ms. Shilpa Aggarwal', 'English', '../images/'],
    ['Ms. Dheeraj', 'Science', '../images/'],
    ['Ms. Saroj Kherwal', 'Mathematics', '../images/'],
    ['Ms. Sanyogita Gupta', 'All Subjects', '../images/'],
    ['Ms. Deepanshi Dutt', 'All Subjects', '../images/'],
    ['Ms. Akansha', 'All Subjects', '../images/'],
    ['Ms. Nikita', 'All Subjects', '../images/'],
    ['Ms. Suman Kumari', 'All Subjects', '../images/'],
    ['Ms. Parmila', 'All Subjects', '../images/'],
    ['Ms. Kusum Bhindwar', 'All Subjects', '../images/'],
    ['Ms. Manisha Gupta', 'All Subjects', '../images/'],
    ['Ms. Sunita Singh', 'All Subjects', '../images/'],
    ['Ms. Vani', 'All Subjects', '../images/'],
    ['Mr. Ravi Yadav', 'PTI / Yoga Teacher', '../images/'],
    ['Ms. Shashi', 'Librarian', '../images/']
];